/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir.pelanggan;

/**
 *
 * @author USER
 */
public class ViewPelanggan extends javax.swing.JFrame {
    private Controller C = new Controller();

    /**
     * Creates new form ViewPelanggan
     */
    public ViewPelanggan() {
        initComponents();
        C.tampildata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pelanggan = new rojerusan.RSTableMetro();
        txt_cari = new rojerusan.RSMetroTextPlaceHolder();
        txt_id = new rojerusan.RSMetroTextPlaceHolder();
        txt_nama = new rojerusan.RSMetroTextPlaceHolder();
        txt_alamat = new rojerusan.RSMetroTextPlaceHolder();
        txt_no = new rojerusan.RSMetroTextPlaceHolder();
        simpan = new rojeru_san.RSButton();
        ubah = new rojeru_san.RSButton();
        hapus = new rojeru_san.RSButton();
        clear = new rojeru_san.RSButton();
        rSButton1 = new rojeru_san.RSButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Pelanggan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        tabel_pelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_pelanggan.setColorBackgoundHead(new java.awt.Color(0, 102, 0));
        tabel_pelanggan.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tabel_pelanggan.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tabel_pelanggan.setColorSelBackgound(new java.awt.Color(153, 153, 153));
        tabel_pelanggan.setRowHeight(30);
        tabel_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_pelanggan);

        txt_cari.setForeground(new java.awt.Color(0, 0, 0));
        txt_cari.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_cari.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_cari.setPhColor(new java.awt.Color(0, 0, 0));
        txt_cari.setPlaceholder("Cari Berdasarkan ID atau Nama Pelanggan :");
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });

        txt_id.setForeground(new java.awt.Color(0, 0, 0));
        txt_id.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_id.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_id.setPhColor(new java.awt.Color(0, 0, 0));
        txt_id.setPlaceholder("ID Pelanggan :");

        txt_nama.setForeground(new java.awt.Color(0, 0, 0));
        txt_nama.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_nama.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_nama.setPhColor(new java.awt.Color(0, 0, 0));
        txt_nama.setPlaceholder("Nama Pelanggan :");

        txt_alamat.setForeground(new java.awt.Color(0, 0, 0));
        txt_alamat.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_alamat.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_alamat.setPhColor(new java.awt.Color(0, 0, 0));
        txt_alamat.setPlaceholder("Alamat :");

        txt_no.setForeground(new java.awt.Color(0, 0, 0));
        txt_no.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_no.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_no.setPhColor(new java.awt.Color(0, 0, 0));
        txt_no.setPlaceholder("No.Telp :");

        simpan.setBackground(new java.awt.Color(51, 153, 0));
        simpan.setText("SIMPAN");
        simpan.setColorHover(new java.awt.Color(0, 51, 0));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        ubah.setBackground(new java.awt.Color(51, 153, 0));
        ubah.setText("UBAH");
        ubah.setColorHover(new java.awt.Color(0, 51, 0));
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(51, 153, 0));
        hapus.setText("HAPUS");
        hapus.setColorHover(new java.awt.Color(0, 51, 0));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(51, 153, 0));
        clear.setText("BERSIHKAN");
        clear.setColorHover(new java.awt.Color(0, 51, 0));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        rSButton1.setBackground(new java.awt.Color(51, 153, 0));
        rSButton1.setText("KELUAR");
        rSButton1.setColorHover(new java.awt.Color(0, 51, 0));
        rSButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rSButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addComponent(jScrollPane1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        Pelanggan P = new Pelanggan();
        P.setId_pelanggan(Integer.parseInt(txt_id.getText()));
        P.setNama(txt_nama.getText());
        P.setAlamat(txt_alamat.getText());
        P.setNo(txt_no.getText());
        
        String hasil = C.tambahdata(P);
        System.out.println("hasil");
    }//GEN-LAST:event_simpanActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        Pelanggan P = new Pelanggan();
        P.setId_pelanggan(Integer.parseInt(txt_id.getText()));
        P.setNama(txt_nama.getText());
        P.setAlamat(txt_alamat.getText());
        P.setNo(txt_no.getText());
        
        String hasil = C.edit(P);
        System.out.println("hasil");
    }//GEN-LAST:event_ubahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        Pelanggan P = new Pelanggan();
        P.setId_pelanggan(Integer.parseInt(txt_id.getText()));
        
        String hasil = C.hapus(P);
        System.out.println("hasil");
    }//GEN-LAST:event_hapusActionPerformed

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        // TODO add your handling code here:
        String cari = txt_cari.getText();
        C.cari(cari);
    }//GEN-LAST:event_txt_cariKeyReleased

    private void tabel_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pelangganMouseClicked
        // TODO add your handling code here:
        int baristabel = tabel_pelanggan.getSelectedRow(); //baris

        txt_id.setText(tabel_pelanggan.getValueAt(baristabel, 0).toString());
        txt_nama.setText(tabel_pelanggan.getValueAt(baristabel, 1).toString());
        txt_alamat.setText(tabel_pelanggan.getValueAt(baristabel, 2).toString());
        txt_no.setText(tabel_pelanggan.getValueAt(baristabel, 3).toString());
    }//GEN-LAST:event_tabel_pelangganMouseClicked

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        txt_id.setText("");
      txt_nama.setText("");
      txt_alamat.setText("");
      txt_no.setText("");
      txt_cari.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void rSButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_rSButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton clear;
    private rojeru_san.RSButton hapus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.RSButton rSButton1;
    private rojeru_san.RSButton simpan;
    public static rojerusan.RSTableMetro tabel_pelanggan;
    private rojerusan.RSMetroTextPlaceHolder txt_alamat;
    private rojerusan.RSMetroTextPlaceHolder txt_cari;
    private rojerusan.RSMetroTextPlaceHolder txt_id;
    private rojerusan.RSMetroTextPlaceHolder txt_nama;
    private rojerusan.RSMetroTextPlaceHolder txt_no;
    private rojeru_san.RSButton ubah;
    // End of variables declaration//GEN-END:variables
}
