/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir.produk;

import java.math.BigDecimal;

/**
 *
 * @author USER
 */
public class ViewProduk extends javax.swing.JFrame {
    private Controller C = new Controller();

    /**
     * Creates new form ViewProduk
     */
    
    public ViewProduk() {
        initComponents();
        C.tampildata();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_produk = new rojerusan.RSTableMetro();
        txt_cari = new rojerusan.RSMetroTextPlaceHolder();
        txt_id = new rojerusan.RSMetroTextPlaceHolder();
        txt_nama = new rojerusan.RSMetroTextPlaceHolder();
        txt_harga = new rojerusan.RSMetroTextPlaceHolder();
        txt_stok = new rojerusan.RSMetroTextPlaceHolder();
        simpan = new rojeru_san.RSButton();
        edit = new rojeru_san.RSButton();
        hapus = new rojeru_san.RSButton();
        clear = new rojeru_san.RSButton();
        rSButton1 = new rojeru_san.RSButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pendataan Barang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        tabel_produk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_produk.setColorBackgoundHead(new java.awt.Color(0, 102, 0));
        tabel_produk.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tabel_produk.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tabel_produk.setColorSelBackgound(new java.awt.Color(153, 153, 153));
        tabel_produk.setRowHeight(30);
        tabel_produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_produkMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_produk);

        txt_cari.setForeground(new java.awt.Color(0, 0, 0));
        txt_cari.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_cari.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_cari.setPhColor(new java.awt.Color(0, 0, 0));
        txt_cari.setPlaceholder("Cari Berdasarkan ID atau Nama Produk :");
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });

        txt_id.setForeground(new java.awt.Color(0, 0, 0));
        txt_id.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_id.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_id.setPhColor(new java.awt.Color(0, 0, 0));
        txt_id.setPlaceholder("ID Produk :");

        txt_nama.setForeground(new java.awt.Color(0, 0, 0));
        txt_nama.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_nama.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_nama.setPhColor(new java.awt.Color(0, 0, 0));
        txt_nama.setPlaceholder("Nama Produk :");

        txt_harga.setForeground(new java.awt.Color(0, 0, 0));
        txt_harga.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_harga.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_harga.setPhColor(new java.awt.Color(0, 0, 0));
        txt_harga.setPlaceholder("Harga :");

        txt_stok.setForeground(new java.awt.Color(0, 0, 0));
        txt_stok.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_stok.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_stok.setPhColor(new java.awt.Color(0, 0, 0));
        txt_stok.setPlaceholder("Stok :");

        simpan.setBackground(new java.awt.Color(51, 153, 0));
        simpan.setText("SIMPAN");
        simpan.setColorHover(new java.awt.Color(0, 51, 0));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(51, 153, 0));
        edit.setText("UBAH");
        edit.setColorHover(new java.awt.Color(0, 51, 0));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(51, 153, 0));
        hapus.setText("HAPUS");
        hapus.setColorHover(new java.awt.Color(0, 51, 0));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(51, 153, 0));
        clear.setText("BERSIHKAN");
        clear.setColorHover(new java.awt.Color(0, 51, 0));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        rSButton1.setBackground(new java.awt.Color(51, 153, 0));
        rSButton1.setText("KELUAR");
        rSButton1.setColorHover(new java.awt.Color(0, 51, 0));
        rSButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rSButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane2)))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(txt_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        Produk P = new Produk();
        P.setId_produk(Integer.parseInt(txt_id.getText()));
        P.setNama(txt_nama.getText());
        P.setHarga(new BigDecimal(txt_harga.getText()));
        P.setStok(Integer.parseInt(txt_stok.getText()));
        
        String hasil = C.tambahdata(P);  
        System.out.println("hasil"); 
    }//GEN-LAST:event_simpanActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        Produk P = new Produk();
        P.setId_produk(Integer.parseInt(txt_id.getText()));
        P.setNama(txt_nama.getText());
        P.setHarga(new BigDecimal(txt_harga.getText()));
        P.setStok(Integer.parseInt(txt_stok.getText()));
        
        String hasil = C.edit(P);
        System.out.println("hasil");
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        Produk P = new Produk();
        P.setId_produk(Integer.parseInt(txt_id.getText()));
        
        String hasil = C.hapus(P);
        System.out.println("hasil");
    }//GEN-LAST:event_hapusActionPerformed

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        // TODO add your handling code here:
        String cari = txt_cari.getText();
        C.cari(cari);
    }//GEN-LAST:event_txt_cariKeyReleased

    private void tabel_produkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_produkMouseClicked
        // TODO add your handling code here:
        int baristabel = tabel_produk.getSelectedRow(); //baris

        txt_id.setText(tabel_produk.getValueAt(baristabel, 0).toString());
        txt_nama.setText(tabel_produk.getValueAt(baristabel, 1).toString());
        txt_harga.setText(tabel_produk.getValueAt(baristabel, 2).toString());
        txt_stok.setText(tabel_produk.getValueAt(baristabel, 3).toString());
    }//GEN-LAST:event_tabel_produkMouseClicked

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:

      txt_id.setText("");
      txt_nama.setText("");
      txt_harga.setText("");
      txt_stok.setText("");
      txt_cari.setText("");
    
    }//GEN-LAST:event_clearActionPerformed

    private void rSButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_rSButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton clear;
    private rojeru_san.RSButton edit;
    private rojeru_san.RSButton hapus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private rojeru_san.RSButton rSButton1;
    private rojeru_san.RSButton simpan;
    public static rojerusan.RSTableMetro tabel_produk;
    private rojerusan.RSMetroTextPlaceHolder txt_cari;
    private rojerusan.RSMetroTextPlaceHolder txt_harga;
    private rojerusan.RSMetroTextPlaceHolder txt_id;
    private rojerusan.RSMetroTextPlaceHolder txt_nama;
    private rojerusan.RSMetroTextPlaceHolder txt_stok;
    // End of variables declaration//GEN-END:variables
}
