 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir.detail;

import java.math.BigDecimal;
import javax.swing.JOptionPane;
import kasir.login.ViewLogin;
import kasir.produk.Produk;

/**
 *
 * @author USER
 */
public class ViewBelanja extends javax.swing.JFrame {

    /**
     * Creates new form ViewBelanja
     */
    private ControllerPenjualan C = new ControllerPenjualan();
    private ControllerDetailPenjualan CDP = new ControllerDetailPenjualan();
    public ViewBelanja() {
        initComponents();
        C.tampilPenjualan();
        C.tampil_pelangganID();

        jTabbedPane1.setEnabledAt(1, false);  //untuk form belanja ketutup
        btn_belanja.setEnabled(false);
        label_stok_peringatan.setVisible(false); //supaya tidak tampil dlu
        
//-----------------------------------LOGIN---------------------------------------------------------------------
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_id_produk = new javax.swing.JLabel();
        label_jumlah = new javax.swing.JLabel();
        label_stok_akhir = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txt_id = new rojerusan.RSMetroTextPlaceHolder();
        tgl_penj = new com.toedter.calendar.JDateChooser();
        txt_total_produk = new rojerusan.RSMetroTextPlaceHolder();
        combo_id_pel = new javax.swing.JComboBox<>();
        txt_nama = new rojerusan.RSMetroTextPlaceHolder();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_penjualan = new rojerusan.RSTableMetro();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_detail_penjualan = new rojerusan.RSTableMetro();
        jLabel2 = new javax.swing.JLabel();
        btn_simpan_penj = new rojeru_san.RSButton();
        btn_hapusPenjualan = new rojeru_san.RSButton();
        muat_ulang = new rojeru_san.RSButton();
        btn_belanja = new rojeru_san.RSButton();
        rSButton2 = new rojeru_san.RSButton();
        jPanel3 = new javax.swing.JPanel();
        txt_np_belanja = new rojerusan.RSMetroTextPlaceHolder();
        txt_id_penjualan = new rojerusan.RSMetroTextPlaceHolder();
        txt_produk_belanja = new rojerusan.RSMetroTextPlaceHolder();
        txt_harga_belanja = new rojerusan.RSMetroTextPlaceHolder();
        txt_stok_belanja = new rojerusan.RSMetroTextPlaceHolder();
        btn_PilihBarang = new rojeru_san.RSButton();
        txt_jumlah_belanja = new rojerusan.RSMetroTextPlaceHolder();
        btn_tambah_keranjang = new rojeru_san.RSButton();
        label_stok_peringatan = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_detail_belanja = new rojerusan.RSTableMetro();
        btn_simpanTransaksi = new rojeru_san.RSButton();
        btn_HapusProduk = new rojeru_san.RSButton();
        btn_UbahTransaksi = new rojeru_san.RSButton();
        txt_total_belanja = new rojerusan.RSMetroTextPlaceHolder();

        label_id_produk.setText("jLabel3");

        label_jumlah.setText("jLabel1");

        label_stok_akhir.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        txt_id.setForeground(new java.awt.Color(0, 0, 0));
        txt_id.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_id.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_id.setPhColor(new java.awt.Color(0, 0, 0));
        txt_id.setPlaceholder("Masukan ID Penjualan :");

        tgl_penj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txt_total_produk.setEditable(false);
        txt_total_produk.setForeground(new java.awt.Color(0, 0, 0));
        txt_total_produk.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_total_produk.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_total_produk.setPhColor(new java.awt.Color(0, 0, 0));
        txt_total_produk.setPlaceholder("Total Produk ");

        combo_id_pel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_id_pel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " << Pilih ID Pelanggan >>" }));
        combo_id_pel.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combo_id_pelPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        txt_nama.setEditable(false);
        txt_nama.setForeground(new java.awt.Color(0, 0, 0));
        txt_nama.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_nama.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_nama.setPhColor(new java.awt.Color(0, 0, 0));
        txt_nama.setPlaceholder("Nama Pelanggan");

        tabel_penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_penjualan.setColorBackgoundHead(new java.awt.Color(0, 102, 0));
        tabel_penjualan.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tabel_penjualan.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tabel_penjualan.setColorSelBackgound(new java.awt.Color(153, 153, 153));
        tabel_penjualan.setRowHeight(30);
        tabel_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_penjualanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_penjualan);

        tabel_detail_penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_detail_penjualan.setColorBackgoundHead(new java.awt.Color(0, 102, 0));
        tabel_detail_penjualan.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tabel_detail_penjualan.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tabel_detail_penjualan.setColorSelBackgound(new java.awt.Color(153, 153, 153));
        tabel_detail_penjualan.setRowHeight(30);
        jScrollPane2.setViewportView(tabel_detail_penjualan);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Masukan Tanggal Penjualan :");

        btn_simpan_penj.setBackground(new java.awt.Color(51, 51, 51));
        btn_simpan_penj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        btn_simpan_penj.setText("SIMPAN PENJUALAN");
        btn_simpan_penj.setColorHover(new java.awt.Color(102, 0, 0));
        btn_simpan_penj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan_penjActionPerformed(evt);
            }
        });

        btn_hapusPenjualan.setBackground(new java.awt.Color(51, 51, 51));
        btn_hapusPenjualan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_hapusPenjualan.setText("HAPUS PENJUALAN");
        btn_hapusPenjualan.setColorHover(new java.awt.Color(102, 0, 0));
        btn_hapusPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusPenjualanActionPerformed(evt);
            }
        });

        muat_ulang.setBackground(new java.awt.Color(51, 51, 51));
        muat_ulang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        muat_ulang.setText("MUAT ULANG ");
        muat_ulang.setColorHover(new java.awt.Color(102, 0, 0));
        muat_ulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muat_ulangActionPerformed(evt);
            }
        });

        btn_belanja.setBackground(new java.awt.Color(51, 51, 51));
        btn_belanja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        btn_belanja.setText("BELANJA");
        btn_belanja.setColorHover(new java.awt.Color(102, 0, 0));
        btn_belanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_belanjaActionPerformed(evt);
            }
        });

        rSButton2.setBackground(new java.awt.Color(51, 51, 51));
        rSButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        rSButton2.setText("KELUAR");
        rSButton2.setColorHover(new java.awt.Color(102, 0, 0));
        rSButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tgl_penj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_total_produk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combo_id_pel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 65, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_simpan_penj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(muat_ulang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rSButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_hapusPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_belanja, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tgl_penj, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txt_total_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(combo_id_pel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_simpan_penj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(muat_ulang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_belanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapusPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Penjualan", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        txt_np_belanja.setEditable(false);
        txt_np_belanja.setForeground(new java.awt.Color(0, 0, 0));
        txt_np_belanja.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_np_belanja.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_np_belanja.setPhColor(new java.awt.Color(0, 0, 0));
        txt_np_belanja.setPlaceholder("Nama Pelanggan");

        txt_id_penjualan.setEditable(false);
        txt_id_penjualan.setForeground(new java.awt.Color(0, 0, 0));
        txt_id_penjualan.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_id_penjualan.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_id_penjualan.setPhColor(new java.awt.Color(0, 0, 0));
        txt_id_penjualan.setPlaceholder("ID Penjualan");

        txt_produk_belanja.setEditable(false);
        txt_produk_belanja.setForeground(new java.awt.Color(0, 0, 0));
        txt_produk_belanja.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_produk_belanja.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_produk_belanja.setPhColor(new java.awt.Color(0, 0, 0));
        txt_produk_belanja.setPlaceholder("Nama Barang");

        txt_harga_belanja.setEditable(false);
        txt_harga_belanja.setForeground(new java.awt.Color(0, 0, 0));
        txt_harga_belanja.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_harga_belanja.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_harga_belanja.setPhColor(new java.awt.Color(0, 0, 0));
        txt_harga_belanja.setPlaceholder("Harga ");

        txt_stok_belanja.setEditable(false);
        txt_stok_belanja.setForeground(new java.awt.Color(0, 0, 0));
        txt_stok_belanja.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_stok_belanja.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_stok_belanja.setPhColor(new java.awt.Color(0, 0, 0));
        txt_stok_belanja.setPlaceholder("Stok ");

        btn_PilihBarang.setBackground(new java.awt.Color(51, 51, 51));
        btn_PilihBarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        btn_PilihBarang.setText("PILIH BARANG");
        btn_PilihBarang.setColorHover(new java.awt.Color(102, 0, 0));
        btn_PilihBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PilihBarangActionPerformed(evt);
            }
        });

        txt_jumlah_belanja.setForeground(new java.awt.Color(0, 0, 0));
        txt_jumlah_belanja.setBorderColor(new java.awt.Color(0, 102, 0));
        txt_jumlah_belanja.setBotonColor(new java.awt.Color(255, 51, 51));
        txt_jumlah_belanja.setPhColor(new java.awt.Color(0, 0, 0));
        txt_jumlah_belanja.setPlaceholder("Masukan Jumlah Beli :");

        btn_tambah_keranjang.setBackground(new java.awt.Color(51, 51, 51));
        btn_tambah_keranjang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        btn_tambah_keranjang.setText("TAMBAH KE KERANJANG");
        btn_tambah_keranjang.setColorHover(new java.awt.Color(102, 0, 0));
        btn_tambah_keranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_keranjangActionPerformed(evt);
            }
        });

        label_stok_peringatan.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        label_stok_peringatan.setForeground(new java.awt.Color(255, 0, 0));
        label_stok_peringatan.setText("Maaf jumlah melebihi stok !!");

        tabel_detail_belanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_detail_belanja.setColorBackgoundHead(new java.awt.Color(0, 102, 0));
        tabel_detail_belanja.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tabel_detail_belanja.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tabel_detail_belanja.setColorSelBackgound(new java.awt.Color(153, 153, 153));
        tabel_detail_belanja.setRowHeight(30);
        tabel_detail_belanja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_detail_belanjaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel_detail_belanja);

        btn_simpanTransaksi.setBackground(new java.awt.Color(51, 51, 51));
        btn_simpanTransaksi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        btn_simpanTransaksi.setText("SIMPAN TRANSAKSI");
        btn_simpanTransaksi.setColorHover(new java.awt.Color(102, 0, 0));
        btn_simpanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanTransaksiActionPerformed(evt);
            }
        });

        btn_HapusProduk.setBackground(new java.awt.Color(51, 51, 51));
        btn_HapusProduk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_HapusProduk.setText("HAPUS PRODUK");
        btn_HapusProduk.setColorHover(new java.awt.Color(102, 0, 0));
        btn_HapusProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HapusProdukActionPerformed(evt);
            }
        });

        btn_UbahTransaksi.setBackground(new java.awt.Color(51, 51, 51));
        btn_UbahTransaksi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_UbahTransaksi.setText("UBAH TRANSAKSI");
        btn_UbahTransaksi.setColorHover(new java.awt.Color(102, 0, 0));
        btn_UbahTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UbahTransaksiActionPerformed(evt);
            }
        });

        txt_total_belanja.setEditable(false);
        txt_total_belanja.setForeground(new java.awt.Color(0, 0, 0));
        txt_total_belanja.setBorderColor(new java.awt.Color(204, 0, 0));
        txt_total_belanja.setBotonColor(new java.awt.Color(153, 0, 0));
        txt_total_belanja.setPhColor(new java.awt.Color(0, 0, 0));
        txt_total_belanja.setPlaceholder("Total Belanja");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_produk_belanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_np_belanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jumlah_belanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_harga_belanja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_id_penjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_stok_belanja, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_PilihBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_tambah_keranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_simpanTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btn_HapusProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btn_UbahTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150)
                                .addComponent(txt_total_belanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(label_stok_peringatan, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_np_belanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_id_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_PilihBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_produk_belanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_harga_belanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_stok_belanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_jumlah_belanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_tambah_keranjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_stok_peringatan)
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_simpanTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_HapusProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_UbahTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_total_belanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Belanja", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpan_penjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan_penjActionPerformed
        // TODO add your handling code here:
        Penjualan P = new Penjualan();
        java.util.Date d = tgl_penj.getCalendar().getTime();
        java.sql.Date tanggalTransaksi = new java.sql.Date(d.getTime());

        P.setId_pelanggan(Integer.parseInt(combo_id_pel.getSelectedItem().toString()));
        P.setId_penjualan(Integer.parseInt(txt_id.getText()));
        P.setTgl_penjualan(tanggalTransaksi);
        P.setTotal_harga(new BigDecimal(0));

        String hasil = C.tambahData(P);
        System.out.println(hasil);

        txt_id.setText("");
        txt_nama.setText("");
        combo_id_pel.setSelectedIndex(0);

    }//GEN-LAST:event_btn_simpan_penjActionPerformed

    private void tabel_penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_penjualanMouseClicked
        // TODO add your handling code here:
       int row = tabel_penjualan.getSelectedRow();

        txt_id.setText(tabel_penjualan.getValueAt(row, 0).toString());
        combo_id_pel.setSelectedItem(tabel_penjualan.getValueAt(row, 3).toString());
        String combo = combo_id_pel.getSelectedItem().toString();

        String hasil = C.tampil_tamu(combo);
        txt_nama.setText(hasil);

        btn_belanja.setEnabled(true);

        CDP.tampilDetailPenjualanDua(tabel_penjualan.getValueAt(row, 0).toString()); //ketika tabel detail diklik, akan muncul data di tabel lain
        CDP.tampilDetailPenjualanBelanja(tabel_penjualan.getValueAt(row, 0).toString());//ketika tabel belanja diklik, akan muncul data di tabel lain

        //mengambil semua total belanja
        BigDecimal total = new BigDecimal(0);
        for (int i = 0; i < tabel_detail_belanja.getRowCount(); i++) {
            BigDecimal a = new BigDecimal(tabel_detail_belanja.getValueAt(i, 4).toString());
            total = total.add(a);
        }

        txt_total_belanja.setText("" + total);
        txt_total_produk.setText("" + total);
    }//GEN-LAST:event_tabel_penjualanMouseClicked

    private void combo_id_pelPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_id_pelPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String combo = combo_id_pel.getSelectedItem().toString();

        String hasil = C.tampil_tamu(combo);
        txt_nama.setText(hasil);
    }//GEN-LAST:event_combo_id_pelPopupMenuWillBecomeInvisible

    private void btn_belanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_belanjaActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setEnabledAt(0, false);
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setSelectedIndex(1);

        txt_np_belanja.setText(txt_nama.getText()); //tersembunyi
        txt_id_penjualan.setText(txt_id.getText()); //tersembunyi
    }//GEN-LAST:event_btn_belanjaActionPerformed

    private void btn_tambah_keranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_keranjangActionPerformed
        // TODO add your handling code here:
        int stok_cek = Integer.parseInt(txt_stok_belanja.getText());
        int jumlah_cek = Integer.parseInt(txt_jumlah_belanja.getText());
        if (jumlah_cek > stok_cek) {
            label_stok_peringatan.setVisible(true); //jika melebihi stok muncul notif 
        } else {
            label_stok_peringatan.setVisible(false);

            DetailPenjualan DP = new DetailPenjualan();

            DP.setId_penjualan(Integer.parseInt(txt_id_penjualan.getText()));
            DP.setId_produk(Integer.parseInt(label_id_produk.getText()));
            DP.setJumlah(Integer.parseInt(txt_jumlah_belanja.getText()));

            BigDecimal harga = new BigDecimal(txt_harga_belanja.getText());
            BigDecimal jumlah = new BigDecimal(txt_jumlah_belanja.getText());
            BigDecimal subTotal = jumlah.multiply(harga); //perkalian
            DP.setSub_total(subTotal);

            CDP.tambahData(DP);

            //mengambil semua total belanja
            BigDecimal total = new BigDecimal(0);
            for (int i = 0; i < tabel_detail_belanja.getRowCount(); i++) {
                BigDecimal a = new BigDecimal(tabel_detail_belanja.getValueAt(i, 4).toString());
                total = total.add(a);
            }

            txt_total_belanja.setText("" + total);

//--------------------------STOK-----------------------------------------------------------------------
            Produk P = new Produk(); //ngambil dri class produk 
            int stok = Integer.parseInt(txt_stok_belanja.getText());  //menguraikan variabel
            int jumlah_belanja = Integer.parseInt(txt_jumlah_belanja.getText());

            int sisaStok = stok - jumlah_belanja; //rumusnya
            P.setStok(sisaStok);
            P.setId_produk(Integer.parseInt(label_id_produk.getText())); //ini ngambil id primary (tersembunyi) nya supaya kd keubah semua datanya

            CDP.updateStok(P, DP);
//-----------------------------------------------------------------------------------------------------
            //reset
            txt_produk_belanja.setText("");
            txt_harga_belanja.setText("");
            txt_stok_belanja.setText("");
            txt_jumlah_belanja.setText("");
        }
    }//GEN-LAST:event_btn_tambah_keranjangActionPerformed

    private void btn_simpanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanTransaksiActionPerformed
        // TODO add your handling code here:
        Penjualan P = new Penjualan();

        P.setId_penjualan(Integer.parseInt(txt_id.getText()));
        P.setTotal_harga(new BigDecimal(txt_total_belanja.getText()));

        C.updateData(P);

        JOptionPane.showMessageDialog(null, "berhasil disimpan");

        jTabbedPane1.setEnabledAt(1, false); //form belanja ditutup 
        jTabbedPane1.setEnabledAt(0, true);//form penjualan dibuka 
        jTabbedPane1.setSelectedIndex(0); //aktif di form penjualan
    }//GEN-LAST:event_btn_simpanTransaksiActionPerformed

    private void btn_HapusProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HapusProdukActionPerformed

//-------------------------HAPUS DATA DITABEL----------------------------------------------------
        int row = tabel_detail_belanja.getSelectedRow();
        String id_detail = tabel_detail_belanja.getValueAt(row, 0).toString();

        CDP.hapusItem(id_detail);
        
//-------------------------- STOK DI CANCEL -------------------------------------------------------------------
        int stok_akhir = Integer.parseInt(label_stok_akhir.getText());
        int jumlah = Integer.parseInt(label_jumlah.getText());
        
        int stok_kembali = stok_akhir + jumlah;
        Produk P = new Produk();
        P.setStok(stok_kembali);
        P.setId_produk(Integer.parseInt(label_id_produk.getText()));
        
        DetailPenjualan DP = new DetailPenjualan();
        DP.setId_penjualan(Integer.parseInt(txt_id_penjualan.getText()));
        CDP.updateStok(P, DP);
        
        CDP.tampilDetailPenjualanBelanja(txt_id_penjualan.getText());
        //ketika tabel belanja diklik, akan muncul data di tabel lain       

        
//----------------------Mengambil Semua Total Belanja------------------------------------------------
        BigDecimal total = new BigDecimal(0);
        for (int i = 0; i < tabel_detail_belanja.getRowCount(); i++) {
            BigDecimal a = new BigDecimal(tabel_detail_belanja.getValueAt(i, 4).toString());
            total = total.add(a);
        }
        txt_total_belanja.setText("" + total);
        
    }//GEN-LAST:event_btn_HapusProdukActionPerformed

    private void btn_UbahTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UbahTransaksiActionPerformed
        // TODO add your handling code here:
        Penjualan P = new Penjualan();

        P.setId_penjualan(Integer.parseInt(txt_id.getText()));
        P.setTotal_harga(new BigDecimal(txt_total_belanja.getText()));

        C.updateData(P);

        JOptionPane.showMessageDialog(null, "berhasil disimpan");

        jTabbedPane1.setEnabledAt(1, false); //form belanja ditutup 
        jTabbedPane1.setEnabledAt(0, true);//form penjualan dibuka 
        jTabbedPane1.setSelectedIndex(0); //aktif di form penjualan
    }//GEN-LAST:event_btn_UbahTransaksiActionPerformed

    private void muat_ulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muat_ulangActionPerformed
        // TODO add your handling code here:
        txt_id.setText("");
        txt_nama.setText("");
        txt_total_produk.setText("0");
        combo_id_pel.setSelectedIndex(0);
        CDP.tampilDetailPenjualanDua(txt_id.getText());
        tabel_penjualan.clearSelection();
        btn_belanja.setEnabled(false);
    }//GEN-LAST:event_muat_ulangActionPerformed

    private void btn_hapusPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusPenjualanActionPerformed
        // TODO add your handling code here:
        Penjualan P = new Penjualan();

        P.setId_penjualan(Integer.parseInt(txt_id.getText()));
        String hasil = C.hapusData(P);
        System.out.println(hasil);

        txt_id.setText("");
        txt_nama.setText("");
        txt_total_produk.setText("0");
        combo_id_pel.setSelectedIndex(0);
        CDP.tampilDetailPenjualanDua(txt_id.getText());

        btn_belanja.setEnabled(false);
        
    }//GEN-LAST:event_btn_hapusPenjualanActionPerformed

    private void btn_PilihBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PilihBarangActionPerformed
        // TODO add your handling code here:
         ViewBarang ok = new ViewBarang(null, true);
        ok.setVisible(true);
        
    }//GEN-LAST:event_btn_PilihBarangActionPerformed

    private void tabel_detail_belanjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_detail_belanjaMouseClicked
        // TODO add your handling code here:
        int row = tabel_detail_belanja.getSelectedRow();
        
        String jumlah_awal = tabel_detail_belanja.getValueAt(row, 3).toString();
        String stok_akhir = tabel_detail_belanja.getValueAt(row, 5).toString();
        
        label_jumlah.setText(jumlah_awal);
        label_stok_akhir.setText(stok_akhir);
       
    }//GEN-LAST:event_tabel_detail_belanjaMouseClicked

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_rSButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBelanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBelanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBelanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBelanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBelanja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btn_HapusProduk;
    private rojeru_san.RSButton btn_PilihBarang;
    private rojeru_san.RSButton btn_UbahTransaksi;
    private rojeru_san.RSButton btn_belanja;
    private rojeru_san.RSButton btn_hapusPenjualan;
    private rojeru_san.RSButton btn_simpanTransaksi;
    private rojeru_san.RSButton btn_simpan_penj;
    private rojeru_san.RSButton btn_tambah_keranjang;
    public static javax.swing.JComboBox<String> combo_id_pel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JLabel label_id_produk;
    private javax.swing.JLabel label_jumlah;
    private javax.swing.JLabel label_stok_akhir;
    private javax.swing.JLabel label_stok_peringatan;
    private rojeru_san.RSButton muat_ulang;
    private rojeru_san.RSButton rSButton2;
    public static rojerusan.RSTableMetro tabel_detail_belanja;
    public static rojerusan.RSTableMetro tabel_detail_penjualan;
    public static rojerusan.RSTableMetro tabel_penjualan;
    private com.toedter.calendar.JDateChooser tgl_penj;
    public static rojerusan.RSMetroTextPlaceHolder txt_harga_belanja;
    private rojerusan.RSMetroTextPlaceHolder txt_id;
    private rojerusan.RSMetroTextPlaceHolder txt_id_penjualan;
    private rojerusan.RSMetroTextPlaceHolder txt_jumlah_belanja;
    private rojerusan.RSMetroTextPlaceHolder txt_nama;
    private rojerusan.RSMetroTextPlaceHolder txt_np_belanja;
    public static rojerusan.RSMetroTextPlaceHolder txt_produk_belanja;
    public static rojerusan.RSMetroTextPlaceHolder txt_stok_belanja;
    private rojerusan.RSMetroTextPlaceHolder txt_total_belanja;
    private rojerusan.RSMetroTextPlaceHolder txt_total_produk;
    // End of variables declaration//GEN-END:variables
}
